// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                pgtype.UUID
	OidcIssuer        string
	OidcSubject       string
	Email             string
	CreatedAt         pgtype.Timestamptz
	Username          pgtype.Text
	DisplayName       pgtype.Text
	PreferredCurrency pgtype.Text
	Locale            pgtype.Text
	Timezone          pgtype.Text
	UpdatedAt         pgtype.Timestamptz
}
