// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (oidc_issuer, oidc_subject, email)
VALUES ($1, $2, $3)
RETURNING id, oidc_issuer, oidc_subject, email, created_at
`

type CreateUserParams struct {
	OidcIssuer  string
	OidcSubject string
	Email       string
}

// sqlc query definitions for the canonical user record. Run `just generate`
// to (re)generate typed Go into internal/auth/db/sqlc. Mirrors core's naming
// (CreateUser :one, GetUserBy... :one).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.OidcIssuer, arg.OidcSubject, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIssuerSubject = `-- name: GetUserByIssuerSubject :one
SELECT id, oidc_issuer, oidc_subject, email, created_at FROM users
WHERE oidc_issuer = $1 AND oidc_subject = $2
`

type GetUserByIssuerSubjectParams struct {
	OidcIssuer  string
	OidcSubject string
}

func (q *Queries) GetUserByIssuerSubject(ctx context.Context, arg GetUserByIssuerSubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIssuerSubject, arg.OidcIssuer, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
