// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fair-n-square-co/auth/internal/identity/api (interfaces: IdentityService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/identity.go -package=mocks . IdentityService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/fair-n-square-co/auth/internal/identity/service"
	oidc "github.com/fair-n-square-co/auth/internal/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityService is a mock of IdentityService interface.
type MockIdentityService struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceMockRecorder
	isgomock struct{}
}

// MockIdentityServiceMockRecorder is the mock recorder for MockIdentityService.
type MockIdentityServiceMockRecorder struct {
	mock *MockIdentityService
}

// NewMockIdentityService creates a new mock instance.
func NewMockIdentityService(ctrl *gomock.Controller) *MockIdentityService {
	mock := &MockIdentityService{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityService) EXPECT() *MockIdentityServiceMockRecorder {
	return m.recorder
}

// ResolveOrProvision mocks base method.
func (m *MockIdentityService) ResolveOrProvision(ctx context.Context, claims oidc.IdentityClaims) (service.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveOrProvision", ctx, claims)
	ret0, _ := ret[0].(service.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveOrProvision indicates an expected call of ResolveOrProvision.
func (mr *MockIdentityServiceMockRecorder) ResolveOrProvision(ctx, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveOrProvision", reflect.TypeOf((*MockIdentityService)(nil).ResolveOrProvision), ctx, claims)
}
